### ISSUE TITLE
Evaluate() function gets unexpected arguments

### ISSUE THREAD

**Issue by nelagamy** [explodinggradients/ragas#944]
This is the code: 
result = evaluate(
    amnesty_qa["eval"], metrics=metrics, llm=azure_model, embeddings=azure_embeddings
)
This is the error: 
{
	"name": "TypeError",
	"message": "evaluate() got an unexpected keyword argument 'llm'",
	"stack": "---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[27], line 1
----> 1 result = evaluate(
      2     amnesty_qa[\"eval\"], metrics=metrics, llm=azure_model, embeddings=azure_embeddings
      3 )
      5 result

TypeError: evaluate() got an unexpected keyword argument 'llm'"
}

**Comment by KaimingFanshi** [comment]
seems like you are using an old version of  ragas.  Try upgrade your ragas package [ pip3 install ragas==0.1.7 ]  should resolve your problem .

**Comment by jjmachan** [comment]
thanks to @KaimingFanshi for helping @nelagamy ❤️

**Comment by Raushan999** [comment]
> seems like you are using an old version of ragas. Try upgrade your ragas package [ pip3 install ragas==0.1.7 ] should resolve your problem .

I'm working on openai==0.28.1, and for that I need ragas<=0.0.18,  But ragas is giving the above discussed error. And I can't just upgrade the ragas, since I can only work with lower version of openai.

Any solutions for this....
